name: Run Postman Tests

on:
  push:
    branches: [main]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Adjust to your desired Node.js version
      - name: Install Newman and htmlexra
        run: npm install -g newman newman-reporter-htmlextra

   


      - name: Run Postman Tests
        run: |
          ./utibenoah/book_api_automation/blob/main/test_newman.s
